# Generated by Django 3.1.4 on 2020-12-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type2',
            field=models.CharField(choices=[('owner', 'owner'), ('seller', 'seller'), ('warehouseman', 'warehouseman')], default='owner', max_length=20),
            preserve_default=False,
        ),
    ]
