# Generated by Django 3.1.4 on 2020-12-16 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_user_user_type2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
