# Generated by Django 3.1.4 on 2020-12-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_auto_20201216_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_type2',
            new_name='user_type',
        ),
    ]
